/**
 * Local id helpers.
 *
 * Claim ids (WC-XXXXX) are generated by the Postgres `claim_id_seq` sequence
 * via the `claims.id DEFAULT` expression — never by this file. We keep a
 * client-side validator so callers (especially Vapi tool handlers) can sanity
 * check ids they receive back from the model.
 */

const CLAIM_ID_PATTERN = /^WC-\d{5,}$/;

export function isClaimId(value: unknown): value is string {
  return typeof value === 'string' && CLAIM_ID_PATTERN.test(value);
}

/**
 * Generate a short, opaque correlation id for log lines that aren't tied to a
 * claim (e.g., a webhook batch). Not cryptographically strong — log only.
 */
export function shortId(prefix = 'evt'): string {
  // ~6 base36 chars of crypto-random entropy; plenty for log correlation.
  const buf = new Uint8Array(4);
  // crypto.getRandomValues is available globally in Node 20.
  crypto.getRandomValues(buf);
  let n = 0;
  for (const b of buf) n = (n << 8) | b;
  // >>> 0 to keep it unsigned 32-bit before toString.
  return `${prefix}_${(n >>> 0).toString(36)}`;
}
